### ISSUE TITLE
Add support for VXT releases

### ISSUE THREAD

**Issue by aussiehuddo** [stumpylog/custom-sub-import#1]
As per my comment on the gist I would like to request support for VXT releases.

VXT releases are published on the RARBG site and are exactly the same as RARBG release but just have audio language other than english (ie. they are for foreign films that haven't been dubbed to english). Thus at least one subtitle is required to be foreced.

File structure of the download is the same:

Movie Name.Year.Language.1080p.BluRay.x265-VXT
     |--->Movie Name.Year.Language.1080p.BluRay.x265-VXT.mp4
     |--->Subs
                |--->3_Italian.srt
                |--->4_English.srt
                |--->5_English.srt
                |--->33_Thai.srt
                |--->etc......

I have found examples ranging from 1 to 3 english subtitles included. I believe logic should be as follows:

1 sub - forced
2 subs - smaller file (greater than 10kb) forced, larger file SDH
3 subs - smallest file just plain (.en), middle file forced, largest file SDH (example of this is The Catholic School (2021) where the smallest file is ~2kb and is just english translation of onscreen text, middle file includes this and dialogue, largest file includes both plus SDH)

I would contribute but don't have knowledge of coding to allow me to.

**Comment by stumpylog** [comment]
Do they only provide movie release or TV shows as well?

**Comment by stumpylog** [comment]
I've made an initial pass at this in feature/vtx_logic.  I haven't yet testing any of my recent changes yet, but the general idea is in.

**Comment by aussiehuddo** [comment]
> Do they only provide movie release or TV shows as well?

Just Movies.

> I've made an initial pass at this in feature/vtx_logic. I haven't yet testing any of my recent changes yet, but the general idea is in.

I will test this when I can.

**Comment by aussiehuddo** [comment]
@stumpylog I can't see the updates in the code. I am happy to test if you make them available.

**Comment by stumpylog** [comment]
The files are in this branch: https://github.com/stumpylog/custom-sub-import/tree/feature/vtx_logic

**Comment by aussiehuddo** [comment]
> The files are in this branch: https://github.com/stumpylog/custom-sub-import/tree/feature/vtx_logic

Seems to work fine for me.

**Comment by stumpylog** [comment]
Great.  I'll merge that branch and close this out.
